routes/admin.php
<?php

use App\Http\Controllers\Admin\HomeServiceBooking\HomeServiceController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

 Route::group(['prefix' => 'api'], function(){
        Route::get('/banners',[App\Http\Controllers\API\BannerAPIController::class, 'index']);
        Route::get('home_service_categories', [App\Http\Controllers\API\ServiceBooking\HomeServiceCategoryAPIController::class, 'index']);
        
    });


Route::group(['middleware'=>['auth']],function (){
    Route::impersonate();
    Route::get('/',[App\Http\Controllers\Admin\HomeController::class, 'settings'])->name('dashboard');
    Route::resource('categories', 'CategoryController');
    Route::get('/get_categories',[App\Http\Controllers\Admin\CategoryController::class, 'get_categories'])->name('get_categories');
    Route::post('categories/destroy_multiple',[App\Http\Controllers\Admin\CategoryController::class,'destroy_multiple'])->name('destroy_multiple');
    Route::resource('coupons', 'CouponController');
    Route::post('coupons/destroy_multiple',[App\Http\Controllers\Admin\CouponController::class,'destroy_multiple'])->name('destroy_multiple_coupon');
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
    Route::resource('admins', 'AdminController');
    // Route::resource('vehicles', 'VehicleController');

    Route::resource('vendorKycs', 'VendorKycController');
    Route::resource('driverKycs', 'DriverKycController');
    Route::resource('reviews', 'ReviewController');
    Route::post('reviews/destroy_multiple',[App\Http\Controllers\Admin\ReviewController::class,'destroy_multiple'])->name('destroy_multiple_review');
    Route::get('/vendorKyc/{id}/approve', [\App\Http\Controllers\Admin\VendorKycController::class,'approve'])->name('vendorKycs.approve');
    Route::get('/vendorKyc/{id}/reject', [\App\Http\Controllers\Admin\VendorKycController::class,'reject'])->name('vendorKycs.reject');

    Route::get('/vendorKyc/{id}/delete', [\App\Http\Controllers\Admin\VendorKycController::class,'delete'])->name('vendorKycs.delete');
    Route::post('/vendorKyc/{id}/storeImage', [\App\Http\Controllers\Admin\VendorKycController::class,'storeImage'])->name('vendorKycs.storeImage');
    Route::get('/vendorKyc/{id}/download', [\App\Http\Controllers\Admin\VendorKycController::class,'download'])->name('vendorKycs.download');

    Route::get('/vendorKyc/approve/all/{id}', [\App\Http\Controllers\Admin\VendorKycController::class,'approveall'])->name('vendorKycs.approveall');
    Route::get('/vendorKyc/reject/all/{id}', [\App\Http\Controllers\Admin\VendorKycController::class,'rejectall'])->name('vendorKycs.rejectall');

    Route::get('/driverKycs/{id}/approve', [\App\Http\Controllers\Admin\DriverKycController::class,'approve'])->name('driverKycs.approve');
    Route::get('/driverKycs/{id}/reject', [\App\Http\Controllers\Admin\DriverKycController::class,'reject'])->name('driverKycs.reject');
    Route::get('/driverKycs/approve/all/{id}', [\App\Http\Controllers\Admin\DriverKycController::class,'approveall'])->name('driverKycs.approveall');
    Route::get('/driverKycs/reject/all/{id}', [\App\Http\Controllers\Admin\DriverKycController::class,'rejectall'])->name('driverKycs.rejectall');
    Route::resource('vendors', 'VendorController');
    // Route::resource('services', 'ServiceController');
    Route::resource('paymentTypes', 'PaymentTypeController');
    Route::resource('serviceTypes', 'ServiceTypeController');
    Route::resource('vehicleTypes', 'VehicleTypeController');
    Route::post('vehicleTypes/destroy_multiple',[App\Http\Controllers\Admin\VehicleTypeController::class,'destroy_multiple'])->name('destroy_multiple_vehicle_type');
    Route::resource('serviceCategories', 'ServiceCategoryController');
    Route::resource('storeCategories', 'StoreCategoryController');
    Route::post('storeCategories/destroy_multiple',[App\Http\Controllers\Admin\StoreCategoryController::class,'destroy_multiple'])->name('destroy_multiple_storeCategories');
    Route::resource('banners', 'BannerController');    
    Route::post('banners/destroy_multiple',[App\Http\Controllers\Admin\BannerController::class,'destroy_multiple'])->name('destroy_multiple_banner');
    Route::resource('send_push', 'NotificationController');
    Route::resource('stores', 'StoreController');
    Route::get('/get_store',[App\Http\Controllers\Admin\StoreController::class, 'get_store'])->name('get_store');
    Route::resource('storeTimings', 'StoreTimingController');
    Route::resource('products', 'ProductController');
    Route::post('products/ProductController',[App\Http\Controllers\Admin\ProductController::class,'destroy_multiple'])->name('destroy_multiple_products');
    Route::resource('productVariants', 'ProductVariantController');
    Route::resource('drivers', 'DriverController');
    Route::resource('addresses', 'AddressController');
    Route::resource('payments', 'PaymentController');
    Route::resource('deliveryFees', 'DeliveryFeeController');
    Route::post('deliveryFees/destroy_multiple',[App\Http\Controllers\Admin\DeliveryFeeController::class,'destroy_multiple'])->name('destroy_multiple_delivery_fee');
    Route::get('logintime/{id}', [\App\Http\Controllers\Admin\DriverController::class,'logintime'])->name('logintime');

    Route::resource('homeOrders', 'HomeOrderController');
    Route::resource('orders', 'OrderController');
    Route::post('orders/changeStatus',[App\Http\Controllers\Admin\OrderController::class,'changeStatus'])->name('changeStatus');
    Route::post('orders/assign',[App\Http\Controllers\Admin\OrderController::class,'assignDriver'])->name('assignDriver');
    Route::post('orders/ping',[App\Http\Controllers\Admin\OrderController::class,'pingDriver'])->name('pingDriver');

    Route::post('service/orders/assign',[App\Http\Controllers\Admin\HomeOrderController::class,'assignServiceDriver'])->name('assignServiceDriver');
    Route::resource('pages', 'PageController');

    Route::group(['prefix' => 'carpool',], function () {
        Route::resource('rides', 'RidesController');
        Route::resource('rideBookings', 'RideBookingController');
    });
    
    
   

    Route::resource('notification', 'NotificationController');
    Route::resource('earnings', 'EarningController');
    Route::post('earnings/destroy_multiple',[App\Http\Controllers\Admin\EarningController::class,'destroy_multiple'])->name('destroy_multiple_earning');
    Route::resource('driverWalletTransactions', 'DriverWalletTransactionController');
    Route::post('driverWalletTransactions/destroy_multiple',[App\Http\Controllers\Admin\DriverWalletTransactionController::class,'destroy_multiple'])->name('destroy_multiple_driverWalletTransactions');
    Route::resource('userWalletTransactions', 'UserWalletTransactionController');
    Route::post('userWalletTransactions/destroy_multiple',[App\Http\Controllers\Admin\UserWalletTransactionController::class,'destroy_multiple'])->name('destroy_multiple_userWalletTransactions');
    Route::get('/earningReport', [\App\Http\Controllers\Admin\EarningReportController::class,'index'])->name('earnings.report.index');
    Route::post('/earningReport', [\App\Http\Controllers\Admin\EarningReportController::class,'generate'])->name('earnings.report.generate');

    Route::resource('zones', 'ZoneController');
    Route::resource('timeSlots','TimeSlotsController');
    //Home Services
    Route::resource('homeServices', 'HomeServiceBooking\HomeServiceController');
    Route::resource('homeServiceCategories', 'HomeServiceBooking\HomeServiceCategoryController');
    Route::get('homeServiceTiming/{id}', [HomeServiceController::class,'homeServiceTiming'])->name('homeService.timing');
    Route::post('homeService/setTiming', [HomeServiceController::class,'setTiming'])->name('homeServices.setTiming');

    Route::resource('faqs', 'FAQController');
    Route::resource('sendmails', 'SendOutMailController');
    Route::post('sendmail', [\App\Http\Controllers\Admin\SendOutMailController::class,'send'])->name('sendmails.send');
    //Import/Export
    Route::get('import-export', [\App\Http\Controllers\Admin\ImportExportController::class,'index'])->name('importExport.index');
    Route::post('import', [\App\Http\Controllers\Admin\ImportExportController::class,'import'])->name('importExport.import');
    Route::post('export', [\App\Http\Controllers\Admin\ImportExportController::class,'export'])->name('importExport.export');
    //Reports
    Route::get('reports', [\App\Http\Controllers\Admin\ReportController::class,'index'])->name('reports.index');
    Route::post('reports', [\App\Http\Controllers\Admin\ReportController::class,'generate'])->name('reports.generate');

    Route::get('settings',[\App\Http\Controllers\Admin\SettingsController::class,'index'])->name('settings.index');
    Route::post('settings',[\App\Http\Controllers\Admin\SettingsController::class,'update'])->name('settings.update');
    Route::post('grant-permission',[App\Http\Controllers\API\RoleAPIController::class,'grant_permission'])->name('grand_permission');
    Route::post('revoke-permission',[App\Http\Controllers\API\RoleAPIController::class,'revoke_permission'])->name('revoke_permission');
    Route::post('filterByZone',[\App\Http\Controllers\Admin\OrderController::class,'filterByZone'])->name('orders.filterByZone');
    
       Route::get('/driversmaps',[\App\Http\Controllers\Admin\TrackingMapsController::class,'getTrackingMaps'])->name('trackingmaps.index');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', [App\Http\Controllers\HomeController::class,'index'])->name('root');
Route::get('/', function () {
    // return view('welcome');
    return redirect('/home');
});

Auth::routes();
Route::middleware(['auth'])->group(function (){
    Route::get('/home', [App\Http\Controllers\Admin\HomeController::class,'settings']);
    Route::get('/getorders',[App\Http\Controllers\Admin\HomeController::class, 'get_orders'])->name('getorders');
 
});
Route::middleware(['auth,vendor'])->group(function () {
    Route::get('/profile', [App\Http\Controllers\Admin\HomeController::class,'profile']);
  
});

Route::get('/page/{slug}', [\App\Http\Controllers\Admin\PageController::class,'show'])->name('page.show');

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.app')
  <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MPB7SLT');</script>
<!-- End Google Tag Manager -->
@section('title', 'Dashboard')
@section('content')
   <!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MPB7SLT"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
    <div class="container">

     <div class="row">
        @can('admins.index')
            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-info">
               <div class="inner">

                  <h5>Total Users :&nbsp;&nbsp; <b>{{$dashboard['users']}}</b></h5>
                  <h5>Today Users :&nbsp;&nbsp;<b>{{$dashboard['today_users']}}</b></h5>
                </div>

                <div class="icon">
                  <i class="ion ion-bag"></i>
                </div>
                {{-- <a   href="{{ route('admin.users.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a> --}}
              </div>
            </div>

            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-warning">
                <div class="inner">

                  <h5>Total Driver     :&nbsp;&nbsp;<b>{{$dashboard['driver']}}</b></h5>
                  <h5>Pending Approval :&nbsp;&nbsp;<b>{{$dashboard['pending_driver']}}</b></h5>
                </div>
                <div class="icon">
                  <i class="ion ion-person-add"></i>
                </div>
                {{-- <a   href="{{ route('admin.drivers.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a> --}}
              </div>
            </div>


            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                <div class="inner">

                    <h5>Total Vendors    :&nbsp;&nbsp; <b>{{$dashboard['vendor']}}</b></h5>
                    <h5>Pending Approval :&nbsp;&nbsp;<b>{{$dashboard['pending_vendor']}}</b></h5>

                </div>
                <div class="icon">
                    <i class="ion ion-stats-bars"></i>
                </div>
                {{-- <a   href="{{ route('admin.vendors.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a> --}}
                </div>
            </div>


            @endcan
            <!-- ./col -->
            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-info">
                <div class="inner">

                  <h5>Total Earnings :&nbsp;&nbsp; <b>₹{{$dashboard['earning']}}</b></h5>
                  <h5>Today Earnings :&nbsp;&nbsp;<b>₹{{$dashboard['today_earning']}}</b></h5>

                </div>
                <div class="icon">
                  <i class="ion ion-pie-graph"></i>
                </div>
                {{-- <a  href="{{ route('admin.earnings.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a> --}}
              </div>
            </div>
            <!-- ./col -->
                
            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-info">
                <div class="inner">

                  <h5>Total Orders      :&nbsp;&nbsp;<b>{{$dashboard['orders']}}</b></h5>
                  <h5>Today Orders      :&nbsp;&nbsp;<b>{{$dashboard['today_orders']}}</b></h5>
                  <h5>Unassigned Orders :&nbsp;&nbsp;<b>{{$dashboard['unassigned_orders']}}</b></h5>
                </div>
                <div class="icon">
                  <i class="ion ion-pie-graph"></i>
                </div>
                {{-- <a  href="{{ route('admin.orders.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a> --}}
              </div>
            </div>
            <!-- ./col -->

            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-warning">
                <div class="inner">

                  <h5>Total Admin Commission: &nbsp;&nbsp;<b>₹{{$dashboard['admin_commision']}}</b></h5>
                  <h5>Today Admin Commission: &nbsp;&nbsp;<b>₹{{$dashboard['today_admin_commision']}}</b></h5>
                  <!-- <h5>Unassigned Orders :&nbsp;&nbsp;<b>{{$dashboard['unassigned_orders']}}</b></h5> -->
                </div>
                <div class="icon">
                  <i class="ion ion-pie-graph"></i>
                </div>
                <!-- <a  href="{{ route('admin.orders.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a> -->
              </div>
            </div>
            <!-- ./col -->

            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-success">
                <div class="inner">

                  <h5>Total Tax: &nbsp;&nbsp;<b>₹{{$dashboard['tax']}}</b></h5>
                  <h5>Today Tax: &nbsp;&nbsp;<b>₹{{$dashboard['today_tax']}}</b></h5>
                  <!-- <h5>Unassigned Orders :&nbsp;&nbsp;<b>{{$dashboard['unassigned_orders']}}</b></h5> -->
                </div>
                <div class="icon">
                  <i class="ion ion-pie-graph"></i>
                </div>
                <!-- <a  href="{{ route('admin.orders.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a> -->
              </div>
            </div>
            <!-- ./col -->

            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-info">
                <div class="inner">

                  <h5>Total Delivery Fee: &nbsp;&nbsp;<b>₹{{$dashboard['delivery_fee']}}</b></h5>
                  <h5>Today Delivery Fee: &nbsp;&nbsp;<b>₹{{$dashboard['today_delivery_fee']}}</b></h5>
                  <!-- <h5>Unassigned Orders :&nbsp;&nbsp;<b>{{$dashboard['unassigned_orders']}}</b></h5> -->
                </div>
                <div class="icon">
                  <i class="ion ion-pie-graph"></i>
                </div>
                <!-- <a  href="{{ route('admin.orders.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a> -->
              </div>
            </div>
            <!-- ./col -->

          </div>

    </div>
@endsection

@push('third_party_scripts')
    <script src="{{ asset('js/app.js') }}"></script>
    <script>
        Echo.channel("order.admin.178").listen("data", (e) => {
            console.log("Data received");
            console.log(e);
            // playSound("{{ asset('audio/notification.wav') }}");
        }).subscribed(() => {
            console.log("Subscribed");
            console.log(Echo.socketId());
        });

        function playSound(url) {
            var a = new Audio(url);
            a.play();
        }
    </script>
@endpush

resources/views/admin/home.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">

    </div>
</div>
@endsection

resources/views/admin/profile.blade.php
@extends('admin.layouts.app')
@section('title','Profile')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                    {{__('roles.roles')}}
                    </h3>
                </div>

                <div class="card-body">
                    <div class="form-group col-sm-6">
                        <label for="name">Name</label>
                        <input id="name" name="name" value="{{$user->name}}"  type="text" class="form-control"/>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="email">Email</label>
                        <input id="email" name="email" value="{{$user->email}}"  type="text" class="form-control"/>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="mobile">Mobile</label>
                        <input id="mobile" name="mobile" value="{{$user->mobile}}"  type="text" class="form-control"/>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="wallet_balance">Wallet Balance</label>
                        <input id="wallet_balance" name="wallet_balance" value="{{$user->wallet_balance}}"  type="text" class="form-control"/>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="password">Password</label>
                        <input id="password" name="wallet_balance" autocomplete="off" type="text" class="form-control"/>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="password_confirmation">Confirm Password</label>
                        <input id="password_confirmation" name="password_confirmation" autocomplete="off" type="text" class="form-control"/>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="user_type">User Type</label>
                        <select name="role" class="form-control select2">
                            @foreach ($usertype as $type)
                                <option value="{{$type}}">{{$type}}</option>    
                            @endforeach
                        </select>
                        <input id="user_type" name="user_type" value="{{$user->wallet_balance}}"  type="text" class="form-control"/>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="user_type">Role</label>
                        <select name="role" class="form-control select2">
                            @foreach ($roles as $role)
                                <option value="{{$role->name}}">{{$role->name}}</option>    
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="card-footer">
                    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                    <a href="{{ route('admin.roles.index') }}" class="btn btn-default">
                        @lang('lang.cancel')
                     </a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/settings.blade.php
@extends('admin.layouts.app')
@section('title','Setting')

@prepend('page_css')
<style type="text/css">
    .accordion_card{
        background-color: #FFF;
        border: 2px solid #0084DA;
        margin-bottom: 10px;
        border-radius: 5px;
    }
    .accordian_body{
        border-top: 2px solid #0084DA;
    }
</style>
@endprepend

@section('content')
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                    {{__('roles.roles')}}
                    </h3>
                </div>

                <div class="card-body">
                    <div class="form-group col-sm-12">
                        <label for="name">Name</label>
                        <input id="name" value="{{$role->name}}"  type="text" class="form-control"/>
                    </div>

                </div>
                <div class="card-footer">
                    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                    <a href="{{ route('admin.roles.index') }}" class="btn btn-default">
                        @lang('lang.cancel')
                     </a>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                    <i class="fas fa-cog"></i>
                    {{__('roles.manage_permissions')}}
                    </h3>
                </div>
                <div class="card-body">
                    <div class="accordion" id="accordionExample">
                        @foreach ($permissions as $key => $permission)
                            <div class="accordion_card">
                                <div class="accordian_header">
                                    <h2 class="mb-0">
                                        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#{{$key}}" aria-expanded="false" aria-controls="collapseThree">
                                            {{ucfirst($key)}}
                                        </button>
                                    </h2>
                                </div>
                                <div id="{{$key}}" class="collapse accordian_body" aria-labelledby="headingThree" data-parent="#accordionExample">
                                    <div class="card-body">
                                        <div class="row">
                                            @foreach ($permission as $item)
                                                <div class="col-md-3">
                                                    <div class="form-group">
                                                        <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
                                                            <input type="checkbox" @if($item['granted']) checked @endif class="custom-control-input permission" id="{{$item['name']}}">
                                                            <label class="custom-control-label" for="{{$item['name']}}">{{ucfirst(substr($item['name'],strpos($item['name'],'.') + 1,strlen($item['name'])))}}</label>
                                                        </div>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>

                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@prepend('page_scripts')
<script type="text/javascript">
    $( document ).ready(function() {
        $('input[type="checkbox"].permission').on('change', function (event) {
            var url = "";
            if(this.checked) {
                url = "{{route('admin.grand_permission')}}";
            }else{
                url = "{{route('admin.revoke_permission')}}";
            }

            $.ajax({
                method: "POST",
                url: url,
                data: {_token: "{{csrf_token()}}", role_name: '{{$role->name}}', permission_name: $(this).attr('id')}
            })
            .done(function (msg) {
                if(msg.message == 'Permission revoked') {
                    toastr.error(msg.message);
                }else {
                    toastr.success('Permission granted')
                }
            });

        });
    });
</script>
@endprepend