routes/admin.php
<?php

use App\Http\Controllers\Admin\HomeServiceBooking\HomeServiceController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

 Route::group(['prefix' => 'api'], function(){
        Route::get('/banners',[App\Http\Controllers\API\BannerAPIController::class, 'index']);
        Route::get('home_service_categories', [App\Http\Controllers\API\ServiceBooking\HomeServiceCategoryAPIController::class, 'index']);
        
    });


Route::group(['middleware'=>['auth']],function (){
    Route::impersonate();
    Route::get('/',[App\Http\Controllers\Admin\HomeController::class, 'settings'])->name('dashboard');
    Route::resource('categories', 'CategoryController');
    Route::get('/get_categories',[App\Http\Controllers\Admin\CategoryController::class, 'get_categories'])->name('get_categories');
    Route::post('categories/destroy_multiple',[App\Http\Controllers\Admin\CategoryController::class,'destroy_multiple'])->name('destroy_multiple');
    Route::resource('coupons', 'CouponController');
    Route::post('coupons/destroy_multiple',[App\Http\Controllers\Admin\CouponController::class,'destroy_multiple'])->name('destroy_multiple_coupon');
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
    Route::resource('admins', 'AdminController');
    // Route::resource('vehicles', 'VehicleController');

    Route::resource('vendorKycs', 'VendorKycController');
    Route::resource('driverKycs', 'DriverKycController');
    Route::resource('reviews', 'ReviewController');
    Route::post('reviews/destroy_multiple',[App\Http\Controllers\Admin\ReviewController::class,'destroy_multiple'])->name('destroy_multiple_review');
    Route::get('/vendorKyc/{id}/approve', [\App\Http\Controllers\Admin\VendorKycController::class,'approve'])->name('vendorKycs.approve');
    Route::get('/vendorKyc/{id}/reject', [\App\Http\Controllers\Admin\VendorKycController::class,'reject'])->name('vendorKycs.reject');

    Route::get('/vendorKyc/{id}/delete', [\App\Http\Controllers\Admin\VendorKycController::class,'delete'])->name('vendorKycs.delete');
    Route::post('/vendorKyc/{id}/storeImage', [\App\Http\Controllers\Admin\VendorKycController::class,'storeImage'])->name('vendorKycs.storeImage');
    Route::get('/vendorKyc/{id}/download', [\App\Http\Controllers\Admin\VendorKycController::class,'download'])->name('vendorKycs.download');

    Route::get('/vendorKyc/approve/all/{id}', [\App\Http\Controllers\Admin\VendorKycController::class,'approveall'])->name('vendorKycs.approveall');
    Route::get('/vendorKyc/reject/all/{id}', [\App\Http\Controllers\Admin\VendorKycController::class,'rejectall'])->name('vendorKycs.rejectall');

    Route::get('/driverKycs/{id}/approve', [\App\Http\Controllers\Admin\DriverKycController::class,'approve'])->name('driverKycs.approve');
    Route::get('/driverKycs/{id}/reject', [\App\Http\Controllers\Admin\DriverKycController::class,'reject'])->name('driverKycs.reject');
    Route::get('/driverKycs/approve/all/{id}', [\App\Http\Controllers\Admin\DriverKycController::class,'approveall'])->name('driverKycs.approveall');
    Route::get('/driverKycs/reject/all/{id}', [\App\Http\Controllers\Admin\DriverKycController::class,'rejectall'])->name('driverKycs.rejectall');
    Route::resource('vendors', 'VendorController');
    // Route::resource('services', 'ServiceController');
    Route::resource('paymentTypes', 'PaymentTypeController');
    Route::resource('serviceTypes', 'ServiceTypeController');
    Route::resource('vehicleTypes', 'VehicleTypeController');
    Route::post('vehicleTypes/destroy_multiple',[App\Http\Controllers\Admin\VehicleTypeController::class,'destroy_multiple'])->name('destroy_multiple_vehicle_type');
    Route::resource('serviceCategories', 'ServiceCategoryController');
    Route::resource('storeCategories', 'StoreCategoryController');
    Route::post('storeCategories/destroy_multiple',[App\Http\Controllers\Admin\StoreCategoryController::class,'destroy_multiple'])->name('destroy_multiple_storeCategories');
    Route::resource('banners', 'BannerController');    
    Route::post('banners/destroy_multiple',[App\Http\Controllers\Admin\BannerController::class,'destroy_multiple'])->name('destroy_multiple_banner');
    Route::resource('send_push', 'NotificationController');
    Route::resource('stores', 'StoreController');
    Route::get('/get_store',[App\Http\Controllers\Admin\StoreController::class, 'get_store'])->name('get_store');
    Route::resource('storeTimings', 'StoreTimingController');
    Route::resource('products', 'ProductController');
    Route::post('products/ProductController',[App\Http\Controllers\Admin\ProductController::class,'destroy_multiple'])->name('destroy_multiple_products');
    Route::resource('productVariants', 'ProductVariantController');
    Route::resource('drivers', 'DriverController');
    Route::resource('addresses', 'AddressController');
    Route::resource('payments', 'PaymentController');
    Route::resource('deliveryFees', 'DeliveryFeeController');
    Route::post('deliveryFees/destroy_multiple',[App\Http\Controllers\Admin\DeliveryFeeController::class,'destroy_multiple'])->name('destroy_multiple_delivery_fee');
    Route::get('logintime/{id}', [\App\Http\Controllers\Admin\DriverController::class,'logintime'])->name('logintime');

    Route::resource('homeOrders', 'HomeOrderController');
    Route::resource('orders', 'OrderController');
    Route::post('orders/changeStatus',[App\Http\Controllers\Admin\OrderController::class,'changeStatus'])->name('changeStatus');
    Route::post('orders/assign',[App\Http\Controllers\Admin\OrderController::class,'assignDriver'])->name('assignDriver');
    Route::post('orders/ping',[App\Http\Controllers\Admin\OrderController::class,'pingDriver'])->name('pingDriver');

    Route::post('service/orders/assign',[App\Http\Controllers\Admin\HomeOrderController::class,'assignServiceDriver'])->name('assignServiceDriver');
    Route::resource('pages', 'PageController');

    Route::group(['prefix' => 'carpool',], function () {
        Route::resource('rides', 'RidesController');
        Route::resource('rideBookings', 'RideBookingController');
    });
    
    
   

    Route::resource('notification', 'NotificationController');
    Route::resource('earnings', 'EarningController');
    Route::post('earnings/destroy_multiple',[App\Http\Controllers\Admin\EarningController::class,'destroy_multiple'])->name('destroy_multiple_earning');
    Route::resource('driverWalletTransactions', 'DriverWalletTransactionController');
    Route::post('driverWalletTransactions/destroy_multiple',[App\Http\Controllers\Admin\DriverWalletTransactionController::class,'destroy_multiple'])->name('destroy_multiple_driverWalletTransactions');
    Route::resource('userWalletTransactions', 'UserWalletTransactionController');
    Route::post('userWalletTransactions/destroy_multiple',[App\Http\Controllers\Admin\UserWalletTransactionController::class,'destroy_multiple'])->name('destroy_multiple_userWalletTransactions');
    Route::get('/earningReport', [\App\Http\Controllers\Admin\EarningReportController::class,'index'])->name('earnings.report.index');
    Route::post('/earningReport', [\App\Http\Controllers\Admin\EarningReportController::class,'generate'])->name('earnings.report.generate');

    Route::resource('zones', 'ZoneController');
    Route::resource('timeSlots','TimeSlotsController');
    //Home Services
    Route::resource('homeServices', 'HomeServiceBooking\HomeServiceController');
    Route::resource('homeServiceCategories', 'HomeServiceBooking\HomeServiceCategoryController');
    Route::get('homeServiceTiming/{id}', [HomeServiceController::class,'homeServiceTiming'])->name('homeService.timing');
    Route::post('homeService/setTiming', [HomeServiceController::class,'setTiming'])->name('homeServices.setTiming');

    Route::resource('faqs', 'FAQController');
    Route::resource('sendmails', 'SendOutMailController');
    Route::post('sendmail', [\App\Http\Controllers\Admin\SendOutMailController::class,'send'])->name('sendmails.send');
    //Import/Export
    Route::get('import-export', [\App\Http\Controllers\Admin\ImportExportController::class,'index'])->name('importExport.index');
    Route::post('import', [\App\Http\Controllers\Admin\ImportExportController::class,'import'])->name('importExport.import');
    Route::post('export', [\App\Http\Controllers\Admin\ImportExportController::class,'export'])->name('importExport.export');
    //Reports
    Route::get('reports', [\App\Http\Controllers\Admin\ReportController::class,'index'])->name('reports.index');
    Route::post('reports', [\App\Http\Controllers\Admin\ReportController::class,'generate'])->name('reports.generate');

    Route::get('settings',[\App\Http\Controllers\Admin\SettingsController::class,'index'])->name('settings.index');
    Route::post('settings',[\App\Http\Controllers\Admin\SettingsController::class,'update'])->name('settings.update');
    Route::post('grant-permission',[App\Http\Controllers\API\RoleAPIController::class,'grant_permission'])->name('grand_permission');
    Route::post('revoke-permission',[App\Http\Controllers\API\RoleAPIController::class,'revoke_permission'])->name('revoke_permission');
    Route::post('filterByZone',[\App\Http\Controllers\Admin\OrderController::class,'filterByZone'])->name('orders.filterByZone');
    
       Route::get('/driversmaps',[\App\Http\Controllers\Admin\TrackingMapsController::class,'getTrackingMaps'])->name('trackingmaps.index');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', [App\Http\Controllers\HomeController::class,'index'])->name('root');
Route::get('/', function () {
    // return view('welcome');
    return redirect('/home');
});

Auth::routes();
Route::middleware(['auth'])->group(function (){
    Route::get('/home', [App\Http\Controllers\Admin\HomeController::class,'settings']);
    Route::get('/getorders',[App\Http\Controllers\Admin\HomeController::class, 'get_orders'])->name('getorders');
 
});
Route::middleware(['auth,vendor'])->group(function () {
    Route::get('/profile', [App\Http\Controllers\Admin\HomeController::class,'profile']);
  
});

Route::get('/page/{slug}', [\App\Http\Controllers\Admin\PageController::class,'show'])->name('page.show');

resources/views/admin/admins/create.blade.php
@extends('admin.layouts.app')

@section('title',trans('lang.add_new')." ".trans('models/admins.singular'))

@section('content')
    <div class="content">

        @include('flash::message')

        <div class="card">

            {!! Form::open(['route' => 'admin.admins.store']) !!}

            <div class="card-body">
                <div class="row">
                    @include('admin.admins.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('admin.admins.index') }}" class="btn btn-default">
                 @lang('lang.cancel')
                </a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/admin/admins/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.admins.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    @can('admins.view')
    <a href="{{ route('admin.admins.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="fa fa-eye"></i>
    </a>
    @endcan
    @can('admins.edit')
    <a href="{{ route('admin.admins.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="fa fa-edit"></i>
    </a>
    @endcan
{{--    @can('admins.delete')--}}
{{--    {!! Form::button('<i class="fa fa-trash"></i>', [--}}
{{--        'type' => 'submit',--}}
{{--        'class' => 'btn btn-danger btn-xs',--}}
{{--        'onclick' => 'return confirm("'.__('lang.are_you_sure').'")'--}}
{{--    ]) !!}--}}
{{--    @endcan--}}
</div>
{!! Form::close() !!}

resources/views/admin/admins/edit.blade.php
@extends('admin.layouts.app')

@section('title',trans('lang.edit')." ".trans('models/admins.singular'))

@section('content')
    <div class="content">

        @include('flash::message')

        <div class="card">

            {!! Form::model($admin, ['route' => ['admin.admins.update', $admin->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('admin.admins.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('admin.admins.index') }}" class="btn btn-default">
                    @lang('lang.cancel')
                 </a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/admin/admins/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', __('models/admins.fields.name').':',['class'=>'required']) !!}
    {!! Form::text('name', null, ['class' => 'form-control','required' => 'true']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('mobile', __('models/admins.fields.mobile').':',['class'=>'required']) !!}
    @if(isset($admin))
    <input type="text" name="mobile" class="form-control" required value="{{$admin->country_code.$admin->mobile}}"/>
    @else
    {!! Form::text('mobile', null, ['class' => 'form-control','required' => 'true','maxlength'=>13,'minlength'=>13]) !!}
    @endif
</div>

<!-- Email Field -->
<!-- <div class="form-group col-sm-6">
    {!! Form::label('mobile', __('models/admins.fields.mobile').':',['class'=>'required']) !!}
    {!! Form::text('mobile', null, ['class' => 'form-control','required' => 'true','maxlength'=>13,'minlength'=>13]) !!}
</div> -->

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', __('models/admins.fields.email').':',['class'=>'required']) !!}
    {!! Form::text('email', null, ['class' => 'form-control','required' => 'true']) !!}
</div>

<!-- Password Field -->
<div class="form-group col-sm-6">
    {!! Form::label('password', __('models/admins.fields.password').':') !!}
    {!! Form::password('password', ['class' => 'form-control']) !!}
    
     @if($errors -> first('password'))
    <div class="alert-danger" >{{$errors -> first('password')}}</div>
    @endif
</div>

@if(@$admin->type != 'Super Admin')
<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('type', __('models/admins.fields.type').':',['class'=>'required']) !!}
    <select name="type[]" class="form-control select2">
        @foreach(\Spatie\Permission\Models\Role::where('name','!=','Super Admin')->get() as $role)
            <option @if(!empty($admin) && $admin->hasRole($role->name)) selected @endif value="{{$role->name}}">{{$role->name}}</option>
        @endforeach
    </select>
</div>
@endif

@if(auth()->user()->type != 'Franchisee')
<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('zone', __('models/admins.fields.zone').':',['class'=>'required']) !!}
    <select name="zones[]" class="form-control select2" multiple required>
        @foreach($zones as $zone)
                <option @if(!empty($admin) && $zone->selected) selected @endif value="{{$zone->id}}">{{$zone->title}}</option>
        @endforeach
    </select>
</div>
@endif
<!-- Active Field -->
<div class="form-group col-sm-6">
    <div class="form-check">
        {!! Form::hidden('active', 0, ['class' => 'form-check-input']) !!}
        {!! Form::checkbox('active', '1', null, ['class' => 'form-check-input']) !!}
        {!! Form::label('active', __('models/admins.fields.active'), ['class' => 'form-check-label']) !!}
    </div>
</div>

<!-- Verified Field -->
<div class="form-group col-sm-6">
    <div class="form-check">
        {!! Form::hidden('verified', 0, ['class' => 'form-check-input']) !!}
        {!! Form::checkbox('verified', '1', null, ['class' => 'form-check-input']) !!}
        {!! Form::label('verified', __('models/admins.fields.verified'), ['class' => 'form-check-label']) !!}
    </div>
</div>

resources/views/admin/admins/index.blade.php
@extends('admin.layouts.app')
@section('title','Admins')
@section('content')
    <div class="content">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
                    <li class="nav-item">
                        <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-list mr-2"></i>{{trans('models/admins.plural')}}</a>
                    </li>
                    @can('admins.create')
                    <li class="nav-item">
                        <a class="nav-link" href="{!! route('admin.admins.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.add')." ".trans('models/admins.singular')}}</a>
                    </li>
                    @endcan
                    @include('admin.layouts.datatables_toolbar', compact('dataTable'))
                </ul>
            </div>

            <div class="card-body">
                @include('admin.admins.table')

                <div class="card-footer clearfix float-right">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/admins/show.blade.php
@extends('admin.layouts.app')

@section('title',trans('lang.view')." ".trans('models/admins.singular'))

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>@lang('models/admins.singular')</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('admin.admins.index') }}">
                         @lang('lang.back')
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('admin.admins.show_fields')
                </div>
            </div>
        </div>
    @if($admin->type == "Vendor")
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">KYC Documents</h3>
                @if(count($admin->kyc) > 0)
                <div class="float-right">
                    <a href="{{route('admin.vendorKycs.approveall',['id'=>$admin->id])}}" type="button" class="btn btn-success btn-sm">Accept All</a>
                    <a href="{{route('admin.vendorKycs.rejectall',['id'=>$admin->id])}}" type="button" class="btn btn-danger btn-sm">Reject All</a>
                </div>
                @endif
            </div>
            <div class="card-body">
                <div class="row">
                    @foreach($admin->kyc as $kycDocument)
                        <div class="col-md-6">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-header">
                                        <div class="row justify-content-end">
                                            <div class="col-md-6">
                                                <h3 class="card-title">{{ $kycDocument->doc_type }}</h3>
                                                <small class="text-muted m-1"> (updated {{$kycDocument->updated_at->diffForHumans()}})</small>
                                            </div>
                                            <div class="col-md-6 justify-content-end">
                                                @if($kycDocument->status == 'UPLOADED')
                                                    <div class="float-right"><span class="badge badge-warning">{{ $kycDocument->status }}</span></div>
                                                @elseif($kycDocument->status == "APPROVED")
                                                    <div class="float-right"><span class="badge badge-success">{{ $kycDocument->status }}</span></div>
                                                @elseif($kycDocument->status == "REJECTED")
                                                    <div class="float-right"><span class="badge badge-danger">{{ $kycDocument->status }}</span></div>
                                                @endif
                                            </div>
                                        </div>

                                    </div>
                                    @if($kycDocument->photo)
                                    <div class="card-body">
                                        <a target="_blank" href="{{$kycDocument->photo}}"><img src="{{$kycDocument->photo}}" class="img-fluid" alt="{{$kycDocument->doc_type}}" style="width:100%;height:100%;"></a>
                                    </div>
                                    @else
                                    <div class="card-body">
                                        <a target="_blank" href="{{asset('')}}"><img src="{{asset('storage/icons/no_image.jpg')}}" class="img-fluid" alt="{{$kycDocument->doc_type}}" style="width:50%;height:50%;"></a>
                                    </div>
                                    @endif
                                    <div class="card-footer">
                                        <a href="{{route('admin.vendorKycs.approve',['id'=>$kycDocument->id])}}" type="button" class="btn btn-success btn-sm" data-toggle="tooltip" title="Accept">Accept</a>
                                        <a href="{{route('admin.vendorKycs.reject',['id'=>$kycDocument->id])}}" type="button" class="btn btn-danger btn-sm" data-toggle="tooltip" title="Reject">Reject</a>
                                        
                                        @if($kycDocument->photo)
                                            <a href="{{$kycDocument->photo}}" download="{{$kycDocument->doc_type}}" type="button" class="btn btn-primary btn-sm" data-toggle="tooltip" title="Download"><i class="fa fa-download"></i></a>
                                            <a href="{{route('admin.vendorKycs.delete',['id'=>$kycDocument->id])}}" type="button" class="btn btn-danger btn-sm" data-toggle="tooltip" title="Delete"><i class="fa fa-window-close"></i></a>
                                        @else
                                        {!! Form::open(['route' => array('admin.vendorKycs.storeImage', $kycDocument->id), 'files' => true]) !!}
                                            <input type="file" name="photo"/>
                                            <input type="submit">
                                        {!! Form::close() !!}
                                        @endif
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                </div>
            </div>
        </div>
        @endif
    </div>
@endsection

resources/views/admin/admins/show_fields.blade.php
<!-- Name Field -->
<div class="col-sm-12">
    {!! Form::label('name', __('models/admins.fields.name').':') !!}
    <p>{{ $admin->name }}</p>
</div>

<!-- Email Field -->
<div class="col-sm-12">
    {!! Form::label('email', __('models/admins.fields.email').':') !!}
    <p>{{ $admin->email }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', __('models/admins.fields.created_at').':') !!}
    <p>{{ $admin->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', __('models/admins.fields.updated_at').':') !!}
    <p>{{ $admin->updated_at }}</p>
</div>

resources/views/admin/admins/table.blade.php
@push('third_party_stylesheets')
    @include('layouts.datatables_css')
@endpush
<div class="table-responsive">
{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>
@push('third_party_scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush