routes/admin.php
use App\Http\Controllers\Admin\HomeServiceBooking\HomeServiceController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

 Route::group(['prefix' => 'api'], function(){
        Route::get('/banners',[App\Http\Controllers\API\BannerAPIController::class, 'index']);
        Route::get('home_service_categories', [App\Http\Controllers\API\ServiceBooking\HomeServiceCategoryAPIController::class, 'index']);
        
    });


Route::group(['middleware'=>['auth']],function (){
    Route::impersonate();
    Route::get('/',[App\Http\Controllers\Admin\HomeController::class, 'settings'])->name('dashboard');
    Route::resource('categories', 'CategoryController');
    Route::get('/get_categories',[App\Http\Controllers\Admin\CategoryController::class, 'get_categories'])->name('get_categories');
    Route::post('categories/destroy_multiple',[App\Http\Controllers\Admin\CategoryController::class,'destroy_multiple'])->name('destroy_multiple');
    Route::resource('coupons', 'CouponController');
    Route::post('coupons/destroy_multiple',[App\Http\Controllers\Admin\CouponController::class,'destroy_multiple'])->name('destroy_multiple_coupon');
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
    Route::resource('admins', 'AdminController');
    // Route::resource('vehicles', 'VehicleController');

    Route::resource('vendorKycs', 'VendorKycController');
    Route::resource('driverKycs', 'DriverKycController');
    Route::resource('reviews', 'ReviewController');
    Route::post('reviews/destroy_multiple',[App\Http\Controllers\Admin\ReviewController::class,'destroy_multiple'])->name('destroy_multiple_review');
    Route::get('/vendorKyc/{id}/approve', [\App\Http\Controllers\Admin\VendorKycController::class,'approve'])->name('vendorKycs.approve');
    Route::get('/vendorKyc/{id}/reject', [\App\Http\Controllers\Admin\VendorKycController::class,'reject'])->name('vendorKycs.reject');

    Route::get('/vendorKyc/{id}/delete', [\App\Http\Controllers\Admin\VendorKycController::class,'delete'])->name('vendorKycs.delete');
    Route::post('/vendorKyc/{id}/storeImage', [\App\Http\Controllers\Admin\VendorKycController::class,'storeImage'])->name('vendorKycs.storeImage');
    Route::get('/vendorKyc/{id}/download', [\App\Http\Controllers\Admin\VendorKycController::class,'download'])->name('vendorKycs.download');

    Route::get('/vendorKyc/approve/all/{id}', [\App\Http\Controllers\Admin\VendorKycController::class,'approveall'])->name('vendorKycs.approveall');
    Route::get('/vendorKyc/reject/all/{id}', [\App\Http\Controllers\Admin\VendorKycController::class,'rejectall'])->name('vendorKycs.rejectall');

    Route::get('/driverKycs/{id}/approve', [\App\Http\Controllers\Admin\DriverKycController::class,'approve'])->name('driverKycs.approve');
    Route::get('/driverKycs/{id}/reject', [\App\Http\Controllers\Admin\DriverKycController::class,'reject'])->name('driverKycs.reject');
    Route::get('/driverKycs/approve/all/{id}', [\App\Http\Controllers\Admin\DriverKycController::class,'approveall'])->name('driverKycs.approveall');
    Route::get('/driverKycs/reject/all/{id}', [\App\Http\Controllers\Admin\DriverKycController::class,'rejectall'])->name('driverKycs.rejectall');
    Route::resource('vendors', 'VendorController');
    // Route::resource('services', 'ServiceController');
    Route::resource('paymentTypes', 'PaymentTypeController');
    Route::resource('serviceTypes', 'ServiceTypeController');
    Route::resource('vehicleTypes', 'VehicleTypeController');
    Route::post('vehicleTypes/destroy_multiple',[App\Http\Controllers\Admin\VehicleTypeController::class,'destroy_multiple'])->name('destroy_multiple_vehicle_type');
    Route::resource('serviceCategories', 'ServiceCategoryController');
    Route::resource('storeCategories', 'StoreCategoryController');
    Route::post('storeCategories/destroy_multiple',[App\Http\Controllers\Admin\StoreCategoryController::class,'destroy_multiple'])->name('destroy_multiple_storeCategories');
    Route::resource('banners', 'BannerController');    
    Route::post('banners/destroy_multiple',[App\Http\Controllers\Admin\BannerController::class,'destroy_multiple'])->name('destroy_multiple_banner');
    Route::resource('send_push', 'NotificationController');
    Route::resource('stores', 'StoreController');
    Route::get('/get_store',[App\Http\Controllers\Admin\StoreController::class, 'get_store'])->name('get_store');
    Route::resource('storeTimings', 'StoreTimingController');
    Route::resource('products', 'ProductController');
    Route::post('products/ProductController',[App\Http\Controllers\Admin\ProductController::class,'destroy_multiple'])->name('destroy_multiple_products');
    Route::resource('productVariants', 'ProductVariantController');
    Route::resource('drivers', 'DriverController');
    Route::resource('addresses', 'AddressController');
    Route::resource('payments', 'PaymentController');
    Route::resource('deliveryFees', 'DeliveryFeeController');
    Route::post('deliveryFees/destroy_multiple',[App\Http\Controllers\Admin\DeliveryFeeController::class,'destroy_multiple'])->name('destroy_multiple_delivery_fee');
    Route::get('logintime/{id}', [\App\Http\Controllers\Admin\DriverController::class,'logintime'])->name('logintime');

    Route::resource('homeOrders', 'HomeOrderController');
    Route::resource('orders', 'OrderController');
    Route::post('orders/changeStatus',[App\Http\Controllers\Admin\OrderController::class,'changeStatus'])->name('changeStatus');
    Route::post('orders/assign',[App\Http\Controllers\Admin\OrderController::class,'assignDriver'])->name('assignDriver');
    Route::post('orders/ping',[App\Http\Controllers\Admin\OrderController::class,'pingDriver'])->name('pingDriver');

    Route::post('service/orders/assign',[App\Http\Controllers\Admin\HomeOrderController::class,'assignServiceDriver'])->name('assignServiceDriver');
    Route::resource('pages', 'PageController');

    Route::group(['prefix' => 'carpool',], function () {
        Route::resource('rides', 'RidesController');
        Route::resource('rideBookings', 'RideBookingController');
    });
    
    
   

    Route::resource('notification', 'NotificationController');
    Route::resource('earnings', 'EarningController');
    Route::post('earnings/destroy_multiple',[App\Http\Controllers\Admin\EarningController::class,'destroy_multiple'])->name('destroy_multiple_earning');
    Route::resource('driverWalletTransactions', 'DriverWalletTransactionController');
    Route::post('driverWalletTransactions/destroy_multiple',[App\Http\Controllers\Admin\DriverWalletTransactionController::class,'destroy_multiple'])->name('destroy_multiple_driverWalletTransactions');
    Route::resource('userWalletTransactions', 'UserWalletTransactionController');
    Route::post('userWalletTransactions/destroy_multiple',[App\Http\Controllers\Admin\UserWalletTransactionController::class,'destroy_multiple'])->name('destroy_multiple_userWalletTransactions');
    Route::get('/earningReport', [\App\Http\Controllers\Admin\EarningReportController::class,'index'])->name('earnings.report.index');
    Route::post('/earningReport', [\App\Http\Controllers\Admin\EarningReportController::class,'generate'])->name('earnings.report.generate');

    Route::resource('zones', 'ZoneController');
    Route::resource('timeSlots','TimeSlotsController');
    //Home Services
    Route::resource('homeServices', 'HomeServiceBooking\HomeServiceController');
    Route::resource('homeServiceCategories', 'HomeServiceBooking\HomeServiceCategoryController');
    Route::get('homeServiceTiming/{id}', [HomeServiceController::class,'homeServiceTiming'])->name('homeService.timing');
    Route::post('homeService/setTiming', [HomeServiceController::class,'setTiming'])->name('homeServices.setTiming');

    Route::resource('faqs', 'FAQController');
    Route::resource('sendmails', 'SendOutMailController');
    Route::post('sendmail', [\App\Http\Controllers\Admin\SendOutMailController::class,'send'])->name('sendmails.send');
    //Import/Export
    Route::get('import-export', [\App\Http\Controllers\Admin\ImportExportController::class,'index'])->name('importExport.index');
    Route::post('import', [\App\Http\Controllers\Admin\ImportExportController::class,'import'])->name('importExport.import');
    Route::post('export', [\App\Http\Controllers\Admin\ImportExportController::class,'export'])->name('importExport.export');
    //Reports
    Route::get('reports', [\App\Http\Controllers\Admin\ReportController::class,'index'])->name('reports.index');
    Route::post('reports', [\App\Http\Controllers\Admin\ReportController::class,'generate'])->name('reports.generate');

    Route::get('settings',[\App\Http\Controllers\Admin\SettingsController::class,'index'])->name('settings.index');
    Route::post('settings',[\App\Http\Controllers\Admin\SettingsController::class,'update'])->name('settings.update');
    Route::post('grant-permission',[App\Http\Controllers\API\RoleAPIController::class,'grant_permission'])->name('grand_permission');
    Route::post('revoke-permission',[App\Http\Controllers\API\RoleAPIController::class,'revoke_permission'])->name('revoke_permission');
    Route::post('filterByZone',[\App\Http\Controllers\Admin\OrderController::class,'filterByZone'])->name('orders.filterByZone');
    
       Route::get('/driversmaps',[\App\Http\Controllers\Admin\TrackingMapsController::class,'getTrackingMaps'])->name('trackingmaps.index');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', [App\Http\Controllers\HomeController::class,'index'])->name('root');
Route::get('/', function () {
    // return view('welcome');
    return redirect('/home');
});

Auth::routes();
Route::middleware(['auth'])->group(function (){
    Route::get('/home', [App\Http\Controllers\Admin\HomeController::class,'settings']);
    Route::get('/getorders',[App\Http\Controllers\Admin\HomeController::class, 'get_orders'])->name('getorders');
 
});
Route::middleware(['auth,vendor'])->group(function () {
    Route::get('/profile', [App\Http\Controllers\Admin\HomeController::class,'profile']);
  
});

Route::get('/page/{slug}', [\App\Http\Controllers\Admin\PageController::class,'show'])->name('page.show');

resources/views/admin/vehicle_types/create.blade.php
@extends('admin.layouts.app')

@section('title',trans('lang.add_new')." ".trans('models/vehicleTypes.singular'))

@section('content')
    <div class="content">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'admin.vehicleTypes.store', 'files' => true]) !!}

            <div class="card-body">
                <div class="row">
                    @include('admin.vehicle_types.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('admin.vehicleTypes.index') }}" class="btn btn-default">
                 @lang('lang.cancel')
                </a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/admin/vehicle_types/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.vehicleTypes.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    @can('vehicleTypes.view')
    <a href="{{ route('admin.vehicleTypes.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="fa fa-eye"></i>
    </a>
    @endcan
    @can('vehicleTypes.edit')
    <a href="{{ route('admin.vehicleTypes.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="fa fa-edit"></i>
    </a>
    @endcan
    @can('vehicleTypes.delete')
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => 'return confirm("'.__('crud.are_you_sure').'")'
    ]) !!}
    @endcan
</div>
{!! Form::close() !!}

resources/views/admin/vehicle_types/edit.blade.php
@extends('admin.layouts.app')

@section('title',trans('lang.edit')." ".trans('models/vehicleTypes.singular'))

@section('content')
    <div class="content">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($vehicleType, ['route' => ['admin.vehicleTypes.update', $vehicleType->id], 'method' => 'patch', 'files' => true]) !!}

            <div class="card-body">
                <div class="row">
                    @include('admin.vehicle_types.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('admin.vehicleTypes.index') }}" class="btn btn-default">
                    @lang('lang.cancel')
                 </a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/admin/vehicle_types/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', __('models/vehicleTypes.fields.name').':',['class'=>'required']) !!}
    {!! Form::text('name', null, ['class' => 'form-control','required'=>'true']) !!}
</div>

<!-- Base Price Field -->
<div class="form-group col-sm-6 pick_drop_felds">
    {!! Form::label('max_passengers', __('models/vehicleTypes.fields.max_passengers').':') !!}
    {!! Form::number('max_passengers', null, ['class' => 'form-control']) !!}
</div>

<!-- Icon Field -->
<div class="form-group col-sm-6">
    {!! Form::label('icon', __('models/vehicleTypes.fields.icon').':') !!}
    <div class="input-group">
        <div class="custom-file">
            {!! Form::file('icon', ['class' => 'custom-file-input']) !!}
            {!! Form::label('icon', 'Choose file', ['class' => 'custom-file-label']) !!}
        </div>
    </div>
</div>
<div class="clearfix"></div>

<!-- Icon Field -->
<div class="form-group col-sm-6">
    {!! Form::label('marker_icon', __('models/vehicleTypes.fields.marker_icon').':') !!}
    <div class="input-group">
        <div class="custom-file">
            {!! Form::file('marker_icon', ['class' => 'custom-file-input']) !!}
            {!! Form::label('marker_icon', 'Choose file', ['class' => 'custom-file-label']) !!}
        </div>
    </div>
</div>
<div class="clearfix"></div>


<!-- Base Distance Field -->


<!-- Base Price Field -->
<div class="form-group col-sm-6 pick_drop_felds">
    {!! Form::label('base_price', __('models/serviceCategories.fields.base_price').':') !!}
    {!! Form::number('base_price', null, ['class' => 'form-control']) !!}
</div>

<!-- Base Km Field -->
<div class="form-group col-sm-6 pick_drop_felds">
    {!! Form::label('base_km', __('models/serviceCategories.fields.base_km').':') !!}
    {!! Form::number('base_km', null, ['class' => 'form-control']) !!}
</div>

<!-- Price Km Field -->
<div class="form-group col-sm-6 pick_drop_felds">
    {!! Form::label('price_km', __('models/serviceCategories.fields.price_km').':') !!}
    {!! Form::number('price_km', null, ['class' => 'form-control']) !!}
</div>



<!-- Active Field -->
<div class="form-group col-sm-6">
    <div class="form-check">
        {!! Form::hidden('active', 0, ['class' => 'form-check-input']) !!}
        {!! Form::checkbox('active', '1', null, ['class' => 'form-check-input']) !!}
        {!! Form::label('active', __('models/vehicleTypes.fields.active'), ['class' => 'form-check-label']) !!}
    </div>
</div>

resources/views/admin/vehicle_types/index.blade.php
@extends('admin.layouts.app')
@section('title','Vehicle Types')
@section('content')
    <div class="content">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
                    <li class="nav-item">
                        <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-list mr-2"></i>{{trans('models/vehicleTypes.plural')}}</a>
                    </li>
                    @can('vehicleTypes.create')
                    <li class="nav-item">
                        <a class="nav-link" href="{!! route('admin.vehicleTypes.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.add')." ".trans('models/vehicleTypes.singular')}}</a>
                    </li>
                    @endcan
                    @include('admin.layouts.datatables_toolbar', compact('dataTable'))
                </ul>
            </div>

            <div class="card-body">
                
                {!! Form::open(['route' => ['admin.destroy_multiple_vehicle_type'], 'method' => 'post']) !!}
                    <button type="submit" class="btn btn-danger deleteMultiple" onclick="return confirm('Are you sure?')">Delete Multiple</button>
                    <hr>
                    @include('admin.vehicle_types.table')
                {!! Form::close() !!}
                <div class="card-footer clearfix float-right">
                    <div class="float-right">

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/vehicle_types/show.blade.php
@extends('admin.layouts.app')

@section('title',trans('lang.view')." ".trans('models/vehicleTypes.singular'))

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>@lang('models/vehicleTypes.singular')</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('admin.vehicleTypes.index') }}">
                         @lang('crud.back')
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('admin.vehicle_types.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/vehicle_types/show_fields.blade.php
<!-- Name Field -->
<div class="col-sm-12">
    {!! Form::label('name', __('models/vehicleTypes.fields.name').':') !!}
    <p>{{ $vehicleType->name }}</p>
</div>

<!-- Icon Field -->
<div class="col-sm-12">
    {!! Form::label('icon', __('models/vehicleTypes.fields.icon').':') !!}
    <p>{{ $vehicleType->icon }}</p>
</div>

<!-- Active Field -->
<div class="col-sm-12">
    {!! Form::label('active', __('models/vehicleTypes.fields.active').':') !!}
    <p>{{ $vehicleType->active }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', __('models/vehicleTypes.fields.created_at').':') !!}
    <p>{{ $vehicleType->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', __('models/vehicleTypes.fields.updated_at').':') !!}
    <p>{{ $vehicleType->updated_at }}</p>
</div>

resources/views/admin/vehicle_types/table.blade.php
@push('third_party_stylesheets')
    @include('layouts.datatables_css')
@endpush
<div class="table-responsive">
{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>
@push('third_party_scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
    <script>
    $(document).on('click', '#deleteAll', function() {
        var checkedStatus = this.checked;
        $('.delete').prop('checked', checkedStatus);
    });

</script>
@endpush