routes/admin.php
<?php

use App\Http\Controllers\Admin\HomeServiceBooking\HomeServiceController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

 Route::group(['prefix' => 'api'], function(){
        Route::get('/banners',[App\Http\Controllers\API\BannerAPIController::class, 'index']);
        Route::get('home_service_categories', [App\Http\Controllers\API\ServiceBooking\HomeServiceCategoryAPIController::class, 'index']);
        
    });


Route::group(['middleware'=>['auth']],function (){
    Route::impersonate();
    Route::get('/',[App\Http\Controllers\Admin\HomeController::class, 'settings'])->name('dashboard');
    Route::resource('categories', 'CategoryController');
    Route::get('/get_categories',[App\Http\Controllers\Admin\CategoryController::class, 'get_categories'])->name('get_categories');
    Route::post('categories/destroy_multiple',[App\Http\Controllers\Admin\CategoryController::class,'destroy_multiple'])->name('destroy_multiple');
    Route::resource('coupons', 'CouponController');
    Route::post('coupons/destroy_multiple',[App\Http\Controllers\Admin\CouponController::class,'destroy_multiple'])->name('destroy_multiple_coupon');
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
    Route::resource('admins', 'AdminController');
    // Route::resource('vehicles', 'VehicleController');

    Route::resource('vendorKycs', 'VendorKycController');
    Route::resource('driverKycs', 'DriverKycController');
    Route::resource('reviews', 'ReviewController');
    Route::post('reviews/destroy_multiple',[App\Http\Controllers\Admin\ReviewController::class,'destroy_multiple'])->name('destroy_multiple_review');
    Route::get('/vendorKyc/{id}/approve', [\App\Http\Controllers\Admin\VendorKycController::class,'approve'])->name('vendorKycs.approve');
    Route::get('/vendorKyc/{id}/reject', [\App\Http\Controllers\Admin\VendorKycController::class,'reject'])->name('vendorKycs.reject');

    Route::get('/vendorKyc/{id}/delete', [\App\Http\Controllers\Admin\VendorKycController::class,'delete'])->name('vendorKycs.delete');
    Route::post('/vendorKyc/{id}/storeImage', [\App\Http\Controllers\Admin\VendorKycController::class,'storeImage'])->name('vendorKycs.storeImage');
    Route::get('/vendorKyc/{id}/download', [\App\Http\Controllers\Admin\VendorKycController::class,'download'])->name('vendorKycs.download');

    Route::get('/vendorKyc/approve/all/{id}', [\App\Http\Controllers\Admin\VendorKycController::class,'approveall'])->name('vendorKycs.approveall');
    Route::get('/vendorKyc/reject/all/{id}', [\App\Http\Controllers\Admin\VendorKycController::class,'rejectall'])->name('vendorKycs.rejectall');

    Route::get('/driverKycs/{id}/approve', [\App\Http\Controllers\Admin\DriverKycController::class,'approve'])->name('driverKycs.approve');
    Route::get('/driverKycs/{id}/reject', [\App\Http\Controllers\Admin\DriverKycController::class,'reject'])->name('driverKycs.reject');
    Route::get('/driverKycs/approve/all/{id}', [\App\Http\Controllers\Admin\DriverKycController::class,'approveall'])->name('driverKycs.approveall');
    Route::get('/driverKycs/reject/all/{id}', [\App\Http\Controllers\Admin\DriverKycController::class,'rejectall'])->name('driverKycs.rejectall');
    Route::resource('vendors', 'VendorController');
    // Route::resource('services', 'ServiceController');
    Route::resource('paymentTypes', 'PaymentTypeController');
    Route::resource('serviceTypes', 'ServiceTypeController');
    Route::resource('vehicleTypes', 'VehicleTypeController');
    Route::post('vehicleTypes/destroy_multiple',[App\Http\Controllers\Admin\VehicleTypeController::class,'destroy_multiple'])->name('destroy_multiple_vehicle_type');
    Route::resource('serviceCategories', 'ServiceCategoryController');
    Route::resource('storeCategories', 'StoreCategoryController');
    Route::post('storeCategories/destroy_multiple',[App\Http\Controllers\Admin\StoreCategoryController::class,'destroy_multiple'])->name('destroy_multiple_storeCategories');
    Route::resource('banners', 'BannerController');    
    Route::post('banners/destroy_multiple',[App\Http\Controllers\Admin\BannerController::class,'destroy_multiple'])->name('destroy_multiple_banner');
    Route::resource('send_push', 'NotificationController');
    Route::resource('stores', 'StoreController');
    Route::get('/get_store',[App\Http\Controllers\Admin\StoreController::class, 'get_store'])->name('get_store');
    Route::resource('storeTimings', 'StoreTimingController');
    Route::resource('products', 'ProductController');
    Route::post('products/ProductController',[App\Http\Controllers\Admin\ProductController::class,'destroy_multiple'])->name('destroy_multiple_products');
    Route::resource('productVariants', 'ProductVariantController');
    Route::resource('drivers', 'DriverController');
    Route::resource('addresses', 'AddressController');
    Route::resource('payments', 'PaymentController');
    Route::resource('deliveryFees', 'DeliveryFeeController');
    Route::post('deliveryFees/destroy_multiple',[App\Http\Controllers\Admin\DeliveryFeeController::class,'destroy_multiple'])->name('destroy_multiple_delivery_fee');
    Route::get('logintime/{id}', [\App\Http\Controllers\Admin\DriverController::class,'logintime'])->name('logintime');

    Route::resource('homeOrders', 'HomeOrderController');
    Route::resource('orders', 'OrderController');
    Route::post('orders/changeStatus',[App\Http\Controllers\Admin\OrderController::class,'changeStatus'])->name('changeStatus');
    Route::post('orders/assign',[App\Http\Controllers\Admin\OrderController::class,'assignDriver'])->name('assignDriver');
    Route::post('orders/ping',[App\Http\Controllers\Admin\OrderController::class,'pingDriver'])->name('pingDriver');

    Route::post('service/orders/assign',[App\Http\Controllers\Admin\HomeOrderController::class,'assignServiceDriver'])->name('assignServiceDriver');
    Route::resource('pages', 'PageController');

    Route::group(['prefix' => 'carpool',], function () {
        Route::resource('rides', 'RidesController');
        Route::resource('rideBookings', 'RideBookingController');
    });
    
    
   

    Route::resource('notification', 'NotificationController');
    Route::resource('earnings', 'EarningController');
    Route::post('earnings/destroy_multiple',[App\Http\Controllers\Admin\EarningController::class,'destroy_multiple'])->name('destroy_multiple_earning');
    Route::resource('driverWalletTransactions', 'DriverWalletTransactionController');
    Route::post('driverWalletTransactions/destroy_multiple',[App\Http\Controllers\Admin\DriverWalletTransactionController::class,'destroy_multiple'])->name('destroy_multiple_driverWalletTransactions');
    Route::resource('userWalletTransactions', 'UserWalletTransactionController');
    Route::post('userWalletTransactions/destroy_multiple',[App\Http\Controllers\Admin\UserWalletTransactionController::class,'destroy_multiple'])->name('destroy_multiple_userWalletTransactions');
    Route::get('/earningReport', [\App\Http\Controllers\Admin\EarningReportController::class,'index'])->name('earnings.report.index');
    Route::post('/earningReport', [\App\Http\Controllers\Admin\EarningReportController::class,'generate'])->name('earnings.report.generate');

    Route::resource('zones', 'ZoneController');
    Route::resource('timeSlots','TimeSlotsController');
    //Home Services
    Route::resource('homeServices', 'HomeServiceBooking\HomeServiceController');
    Route::resource('homeServiceCategories', 'HomeServiceBooking\HomeServiceCategoryController');
    Route::get('homeServiceTiming/{id}', [HomeServiceController::class,'homeServiceTiming'])->name('homeService.timing');
    Route::post('homeService/setTiming', [HomeServiceController::class,'setTiming'])->name('homeServices.setTiming');

    Route::resource('faqs', 'FAQController');
    Route::resource('sendmails', 'SendOutMailController');
    Route::post('sendmail', [\App\Http\Controllers\Admin\SendOutMailController::class,'send'])->name('sendmails.send');
    //Import/Export
    Route::get('import-export', [\App\Http\Controllers\Admin\ImportExportController::class,'index'])->name('importExport.index');
    Route::post('import', [\App\Http\Controllers\Admin\ImportExportController::class,'import'])->name('importExport.import');
    Route::post('export', [\App\Http\Controllers\Admin\ImportExportController::class,'export'])->name('importExport.export');
    //Reports
    Route::get('reports', [\App\Http\Controllers\Admin\ReportController::class,'index'])->name('reports.index');
    Route::post('reports', [\App\Http\Controllers\Admin\ReportController::class,'generate'])->name('reports.generate');

    Route::get('settings',[\App\Http\Controllers\Admin\SettingsController::class,'index'])->name('settings.index');
    Route::post('settings',[\App\Http\Controllers\Admin\SettingsController::class,'update'])->name('settings.update');
    Route::post('grant-permission',[App\Http\Controllers\API\RoleAPIController::class,'grant_permission'])->name('grand_permission');
    Route::post('revoke-permission',[App\Http\Controllers\API\RoleAPIController::class,'revoke_permission'])->name('revoke_permission');
    Route::post('filterByZone',[\App\Http\Controllers\Admin\OrderController::class,'filterByZone'])->name('orders.filterByZone');
    
       Route::get('/driversmaps',[\App\Http\Controllers\Admin\TrackingMapsController::class,'getTrackingMaps'])->name('trackingmaps.index');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', [App\Http\Controllers\HomeController::class,'index'])->name('root');
Route::get('/', function () {
    // return view('welcome');
    return redirect('/home');
});

Auth::routes();
Route::middleware(['auth'])->group(function (){
    Route::get('/home', [App\Http\Controllers\Admin\HomeController::class,'settings']);
    Route::get('/getorders',[App\Http\Controllers\Admin\HomeController::class, 'get_orders'])->name('getorders');
 
});
Route::middleware(['auth,vendor'])->group(function () {
    Route::get('/profile', [App\Http\Controllers\Admin\HomeController::class,'profile']);
  
});

Route::get('/page/{slug}', [\App\Http\Controllers\Admin\PageController::class,'show'])->name('page.show');

app/Models/Category.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class Category
 * @package App\Models
 * @version December 7, 2021, 8:09 am UTC
 *
 * @property string $name
 * @property string $image
 * @property integer $parent
 */
class Category extends Model
{

    public $table = 'categories';

    public $fillable = [
        'name',
        'store_id',
        'image',
        'parent'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'store_id' => 'integer',
        'image' => 'string',
        'parent' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'nullable',
        'image' => 'nullable',
        'store_id' => 'nullable',
        'parent' => 'nullable'
    ];

    public function parent_cat(){
        return $this->belongsTo(Category::class,'parent','id');
    }

    public function children(){
        return $this->hasMany(Category::class, 'parent');
    }

    public function products(){
        return $this->hasMany(Product::class,'category_id');
    }

    public function product(){
        return $this->belongsTo(Product::class,'id','parent_category_id');
    }

    public function store(){
        return $this->belongsTo(Store::class);
    }

}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')

@section('title',trans('lang.add_new')." ".trans('models/categories.singular'))

@section('content')
    <div class="content">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'admin.categories.store', 'files' => true]) !!}

            <div class="card-body">
                <div class="row">
                    @include('admin.categories.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('admin.categories.index') }}" class="btn btn-default">
                 @lang('lang.cancel')
                </a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/admin/categories/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.categories.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    @can('categories.view')
    <a href="{{ route('admin.categories.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="fa fa-eye"></i>
    </a>
    @endcan
    @can('categories.edit')
    <a href="{{ route('admin.categories.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="fa fa-edit"></i>
    </a>
    @endcan
    @can('categories.delete')
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => 'return confirm("'.__('crud.are_you_sure').'")'
    ]) !!}
    @endcan
</div>
{!! Form::close() !!}

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('title',trans('lang.edit')." ".trans('models/categories.singular'))

@section('content')
    <div class="content">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($category, ['route' => ['admin.categories.update', $category->id], 'method' => 'patch', 'files' => true]) !!}

            <div class="card-body">
                <div class="row">
                    @include('admin.categories.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('admin.categories.index') }}" class="btn btn-default">
                    @lang('lang.cancel')
                 </a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/admin/categories/fields.blade.php
<!-- Store Field -->
<div class="form-group col-sm-6">
    {!! Form::label('store_id', __('models/categories.fields.store').':',['class'=>'required']) !!}
    <select name="store_id" class="form-control select2" id="store_id" required>
        @foreach($stores as $store)
            <option @if(!empty($category)&&$category->store_id ==  $store->id) selected @endif value="{{ $store->id }}">{{ $store->name }}</option>
        @endforeach
    </select>
</div>

<!-- Parent Field -->
<div class="form-group col-sm-6">
    {!! Form::label('parent', __('models/categories.fields.parent').':') !!}
    <select id="parent" name="parent" class="form-control select2">
    @if(!empty($parent_category[0]->id))    
        @foreach($categories as $cat)
        <option value="{{$cat->id}}"@if($cat->id == $parent_category[0]->id)selected @endif>{{$cat->name}}</option>
        @endforeach
        @endif
    </select>
</div>


<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', __('models/categories.fields.name').':',['class'=>'required']) !!}
    {!! Form::text('name', null, ['class' => 'form-control','required'=>'true']) !!}
</div>

{{--<!-- Image Field -->--}}
{{--<div class="form-group col-sm-6">--}}
{{--    {!! Form::label('image', __('models/categories.fields.image').':') !!}--}}
{{--    <div class="input-group">--}}
{{--        <div class="custom-file">--}}
{{--            {!! Form::file('image', ['class' => 'custom-file-input']) !!}--}}
{{--            {!! Form::label('image', 'Choose file', ['class' => 'custom-file-label']) !!}--}}
{{--        </div>--}}
{{--    </div>--}}
{{--</div>--}}
{{--<div class="clearfix"></div>--}}

@push('third_party_scripts')
    <script type="text/javascript">
        $(document).ready(function (){
            $('#store_id').on('change',function () {
                var storeId = $(this).val();
                console.log(storeId);
                getCategories(storeId);
            }).change();
        });

        function getCategories($storeId) {
            console.log("getCategories");
            $('#parent').select2({
                theme: 'classic',
                ajax: {
                    url: '/api/categories?search=store_id:'+$storeId+';parent:0&searchJoin=and',
                    dataType: 'json',
                    processResults: function (data) {
                        // Transforms the top-level key of the response object from 'items' to 'results'
                        console.log("processResults");
                        if(data.data.length > 0) {
                            return {
                                results: data.data.map(function (item) {
                                    return {
                                        id: item.id,
                                        text: item.name
                                    }
                                })
                            };
                        }
                    }
                }
            });
        }

    </script>
@endpush

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')
@section('title','Categories')
@section('content')
    <div class="content">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
                    <li class="nav-item">
                        <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-list mr-2"></i>{{trans('models/categories.plural')}}</a>
                    </li>
                    @can('categories.create')
                    <li class="nav-item">
                        <a class="nav-link" href="{!! route('admin.categories.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.add')." ".trans('models/categories.singular')}}</a>
                    </li>
                    @endcan

                    @include('admin.layouts.datatables_toolbar', compact('dataTable'))
                </ul>
            </div>

            <div class="card-body">
                {!! Form::open(['route' => ['admin.destroy_multiple'], 'method' => 'post']) !!}
                    <button type="submit" class="btn btn-danger deleteMultiple" onclick="return confirm('Are you sure?')">Delete Multiple</button>
                    <hr>
                    @include('admin.categories.table')
                {!! Form::close() !!}
                
                <div class="card-footer clearfix float-right">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.layouts.app')

@section('title',trans('lang.view')." ".trans('models/categories.singular'))

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>@lang('models/categories.singular')</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('admin.categories.index') }}">
                         @lang('crud.back')
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('admin.categories.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/show_fields.blade.php
<!-- Name Field -->
<div class="col-sm-12">
    {!! Form::label('name', __('models/categories.fields.name').':') !!}
    <p>{{ $category->name }}</p>
</div>

<!-- Image Field -->
<div class="col-sm-12">
    {!! Form::label('image', __('models/categories.fields.image').':') !!}
    <p>{{ $category->image }}</p>
</div>

<!-- Parent Field -->
<div class="col-sm-12">
    {!! Form::label('parent', __('models/categories.fields.parent').':') !!}
    <p>{{ $category->parent }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', __('models/categories.fields.created_at').':') !!}
    <p>{{ $category->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', __('models/categories.fields.updated_at').':') !!}
    <p>{{ $category->updated_at }}</p>
</div>

resources/views/admin/categories/table.blade.php
@push('third_party_stylesheets')
    @include('layouts.datatables_css')
@endpush
<div class="table-responsive">
{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>
@push('third_party_scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
    <script>
        $(document).on('click', '#deleteAll', function() {
            var checkedStatus = this.checked;
            $('.delete').prop('checked', checkedStatus);
        });

    </script>
@endpush